name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk-headless \
          git \
          unzip \
          zip \
          ccache \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          ninja-build \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and dependencies
      run: |
        pip3 install --user --upgrade Cython==0.29.33 buildozer virtualenv

    - name: Initialize Buildozer
      run: |
        python3 -m buildozer init

    - name: Build APK with Buildozer
      run: |
        python3 -m buildozer -v android debug
      env:
        # Let Buildozer manage its own dependencies
        BUILDOLDER_ROOT: ${{ github.workspace }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
        retention-days: 7
