name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: stable
        command: buildozer android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-debug
        path: ${{ steps.buildozer.outputs.filename }}
        if-no-files-found: error
