name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          ccache

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip -d cmdline-tools
        mkdir -p android-sdk
        mv cmdline-tools android-sdk/cmdline-tools
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        # Accept licenses
        yes | android-sdk/cmdline-tools/bin/sdkmanager --licenses
        # Install platform tools and build tools
        android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;33.0.0"
        # Also install the required platform
        android-sdk/cmdline-tools/bin/sdkmanager "platforms;android-33"
        # Add platform-tools and build-tools to PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/33.0.0" >> $GITHUB_PATH

    - name: Install Buildozer and dependencies
      run: |
        pip3 install --user --upgrade Cython==0.29.33 buildozer virtualenv

    - name: Build APK with Buildozer
      run: |
        python3 -m buildozer android debug
      env:
        # Set buildozer to use the current directory
        BUILDOLDER_ROOT: ${{ github.workspace }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
        retention-days: 7
