name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          ccache \
          wget \
          make \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake

    - name: Install Android SDK and Build Tools
      run: |
        # Download Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-8512546_latest.zip -d android-sdk
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # Accept licenses and install required packages
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$PWD/android-sdk --licenses
        android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$PWD/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;25.1.8937393"

    - name: Install Buildozer and dependencies
      run: |
        pip3 install --user --upgrade Cython==0.29.33 buildozer virtualenv

    - name: Configure Buildozer
      run: |
        python3 -m buildozer init
        # Update the spec file with required settings
        sed -i 's/android.sdk = .*/android.sdk = 33/' buildozer.spec
        sed -i 's/android.ndk = .*/android.ndk = 25.1.8937393/' buildozer.spec
        sed -i 's/android.api = .*/android.api = 33/' buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec

    - name: Build APK with Buildozer
      run: |
        python3 -m buildozer -v android debug
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        ANDROID_NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/25.1.8937393

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
        retention-days: 7
