name: Build Calculator APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer in Docker
      uses: thewtex/setup-buildozer@v1

    - name: Build APK
      run: |
        buildozer init
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-debug
        path: bin/*.apk
        if-no-files-found: error
