name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # Explicitly use 22.04 for stability

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies (Ubuntu 22.04+ compatible)
      run: |
        sudo apt update
        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          libtinfo-dev  # This provides libtinfo6, which is sufficient

    - name: Install Buildozer
      run: |
        pip3 install --user "buildozer==1.5.0"  # Pin to stable version
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -l bin/

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
