# .github/workflows/build-apk.yml
name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-full python3-pip python3-venv \
            git zip unzip openjdk-17-jdk \
            libncurses5-dev libncurses6 \
            libstdc++6 libgtk-3-0 \
            libpangocairo-1.0-0 libgstreamer1.0-0 \
            gstreamer1.0-plugins-base libgl1-mesa-dev \
            libgles2-mesa-dev libmtdev-dev xclip xsel libjpeg-dev \
            autoconf libtool pkg-config zlib1g-dev libssl-dev \
            ccache cmake
      
      - name: Set up Python venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade cython==0.29.36
      
      - name: Install Buildozer & Kivy
        run: |
          source venv/bin/activate
          pip install buildozer
          pip install -r requirements.txt
      
      - name: Setup Android environment
        run: |
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
      
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
      
      - name: Cache Buildozer project directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-project-${{ hashFiles('buildozer.spec') }}
      
      - name: Build APK (debug)
        run: |
          source venv/bin/activate
          yes | buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
          if-no-files-found: error
