name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-11-jdk \
          git \
          unzip \
          zip \
          wget \
          cmake

    - name: Install Android SDK and accept licenses
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-8512546_latest.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$PWD/android-sdk --licenses
        android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$PWD/android-sdk "build-tools;33.0.0" "platforms;android-33"

    - name: Install Buildozer
      run: |
        pip3 install --user --upgrade Cython==0.29.33 buildozer

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PWD/android-sdk/cmdline-tools/latest/bin:$PATH
        python3 -m buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
        retention-days: 7
