name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y build-essential git python3-dev
        apt-get install -y aidl

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer kivy

    - name: Set permissions
      run: |
        chmod +x .
        chown -R $USER:$USER .

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: bin/*.apk
        if-no-files-found: error
